server:
  port: 8080
spring:
  application:
    name: spring-security
  thymeleaf:
    cache: false
#  datasource1:
#    url: jdbc:mysql://120.79.166.245:3306/springsecurity?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: 123
#    #password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource2:
    url: jdbc:mysql://120.79.166.245:3306/springsecurity?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
    #password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource1:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.166.245:3306/springsecurity?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    InitialSize: 8
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500