server:
  port: 8888
spring:
  application:
    name: spring-security
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://120.79.166.245:3306/springsecurity?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver